[package]
name = "rust_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = "0.3.15"
rand = "0.8.5"
quad-rand = "0.2.1"
image = "0.24.5"
chrono = "0.4.23"
